
var table_data = [
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001683988",
        "componentClass": "零部件",
        "component": "IBB_螺栓、螺柱",
        "componentDescription": "六角头螺栓",
        "materialName": null,
        "materialStandard": "ASTM F594-2015",
        "industryStandard": "ASME B18.2.1-2013",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-04-18 16:14:00"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001721611",
        "componentClass": "零部件",
        "component": "IBB_螺栓、螺柱",
        "componentDescription": "六角头螺栓",
        "materialName": null,
        "materialStandard": "ASTM F594-2015",
        "industryStandard": "ASME B18.2.1-2013",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-05-09 15:46:07"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001807159",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角平圆头凸缘螺钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7380-2-2011",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-06-21 19:05:21"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001846007",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角平圆头螺钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7380-1-2011",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-07-19 14:32:14"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001850389",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角平圆头凸缘螺钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7380-2-2011",
        "specification": null,
        "additionalInfo": "达克罗4级",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-07-24 11:03:28"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001850548",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角平圆头凸缘螺钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7380-2-2011",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-07-23 13:35:18"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001895041",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角平圆头凸缘螺钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7380-2-2011",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-08-27 16:04:55"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001979319",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角平圆头螺钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7380-1-2011",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-10-22 15:56:39"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001980121",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角平圆头凸缘螺钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7380-2-2011",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-10-23 11:16:40"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000002288700",
        "componentClass": "零部件",
        "component": "IBI_铆钉",
        "componentDescription": "开口型平圆头抽芯铆钉",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO15983-2002",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2019-05-23 19:13:42"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000002375222",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "十字槽半沉头螺钉",
        "materialName": null,
        "materialStandard": "ASTM F593-2017",
        "industryStandard": "ASME B18.6.3-2017",
        "specification": null,
        "additionalInfo": null,
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2019-07-17 16:30:36"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000002375223",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "十字槽沉头螺钉",
        "materialName": null,
        "materialStandard": "ASTM F593-2017",
        "industryStandard": "ASME B18.6.3-2017",
        "specification": null,
        "additionalInfo": "Table12",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2019-07-17 17:00:28"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000002375224",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角沉头螺钉",
        "materialName": null,
        "materialStandard": "ASTM F879-2015",
        "industryStandard": "ASME B18.3-2017",
        "specification": null,
        "additionalInfo": "Table2",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2019-07-17 18:31:05"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000002309126",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角沉头螺钉",
        "materialName": null,
        "materialStandard": "ASTM F879-2015",
        "industryStandard": "ASME B18.3-2017",
        "specification": null,
        "additionalInfo": "Table8",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2019-06-10 11:13:42"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000002309127",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角沉头螺钉",
        "materialName": null,
        "materialStandard": "ASTM F879-2015",
        "industryStandard": "ASME B18.3-2017",
        "specification": null,
        "additionalInfo": "Table 8",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2019-06-10 11:24:46"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001918848",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角圆柱头螺钉",
        "materialName": null,
        "materialStandard": "ISO898-1-2013",
        "industryStandard": "ISO4762-2004",
        "specification": null,
        "additionalInfo": "Table 8",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-09-13 14:54:33"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001918849",
        "componentClass": "零部件",
        "component": "IBC_螺钉",
        "componentDescription": "内六角圆柱头螺钉",
        "materialName": null,
        "materialStandard": "ISO898-1-2013",
        "industryStandard": "ISO4762-2004",
        "specification": null,
        "additionalInfo": "交美特",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-09-13 14:50:52"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001918850",
        "componentClass": "零部件",
        "component": "IBE_螺母",
        "componentDescription": "1型六角螺母",
        "materialName": null,
        "materialStandard": "ISO898-2-2012",
        "industryStandard": "ISO4032-2012",
        "specification": null,
        "additionalInfo": "交美特",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-09-13 14:42:20"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001918851",
        "componentClass": "零部件",
        "component": "IBG_垫片、垫圈",
        "componentDescription": "大平垫圈",
        "materialName": null,
        "materialStandard": "ISO3506-1-2009",
        "industryStandard": "ISO7093-1-2000",
        "specification": null,
        "additionalInfo": "交美特",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-09-13 15:06:48"
    },
    {
        "erpPdmNumber": null,
        "description": null,
        "matName": null,
        "componentNumber": "M000001918852",
        "componentClass": "零部件",
        "component": "IBG_垫片、垫圈",
        "componentDescription": "锯齿状锥形垫圈(普通型)",
        "materialName": null,
        "materialStandard": "NFE25-511-2017",
        "industryStandard": "NFE25-511-2017",
        "specification": null,
        "additionalInfo": "交美特",
        "standardNumber": null,
        "craft": null,
        "part": null,
        "pastProject": null,
        "inventory": null,
        "star": null,
        "frequency": null,
        "supplier": null,
        "movingAveragePrice": null,
        "purchaseCycle": null,
        "purchaseQuantityYerYear": null,
        "consumptionPerYear": null,
        "internationalStandard": null,
        "idt": null,
        "eqv": null,
        "permissionState": null,
        "feature": null,
        "modifyDate": "2018-09-13 15:07:46"
    }
]
